add_newline = true

[character]
success_symbol = "[\uE0B1](bold green)"
error_symbol = "[ ! ](bg:white fg:red bold)[\uE0B0](white)"

[directory]
truncation_length = 100
truncate_to_repo = false

[shell]
powershell_indicator = "\uf17a "
disabled = false

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = false
